name: C# CI Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'OFA-Console-App/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'OFA-Console-App/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore OFA-Console-App/OFA-Console-App.csproj

    - name: Build
      run: dotnet build OFA-Console-App/OFA-Console-App.csproj --no-restore -c Release